package flowcontract

// 本文件承载 Flow 合同生成流程中与 `render` 相关的逻辑。

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// RenderAll 串起合同模型构建与双产物渲染，供 CLI 一次生成文档与 TS 文件。
func RenderAll() (markdown string, typescript string, err error) {
	contract, err := BuildContract()
	if err != nil {
		return "", "", err
	}
	markdown, err = RenderMarkdown(contract)
	if err != nil {
		return "", "", err
	}
	typescript, err = RenderTypeScript(contract)
	if err != nil {
		return "", "", err
	}
	return markdown, typescript, nil
}

// RenderMarkdown 将合同模型渲染为供人阅读的 Flow 合同文档。
func RenderMarkdown(contract *Contract) (string, error) {
	if contract == nil {
		return "", fmt.Errorf("nil contract")
	}

	var b strings.Builder
	b.WriteString("# Flow Contract\n\n")
	b.WriteString("Generated from `protocol/flow/types.go`. Do not hand-edit this file; run `go run ./cmd/flowcontractgen -write`.\n\n")

	b.WriteString("## Enums\n\n")
	for _, enum := range contract.Enums {
		b.WriteString("### " + enum.Name + "\n\n")
		for _, value := range enum.Values {
			b.WriteString("- `" + value + "`\n")
		}
		b.WriteString("\n")
	}

	b.WriteString("## Node Kind To Spec Mapping\n\n")
	b.WriteString("| kind | spec type |\n")
	b.WriteString("|---|---|\n")
	for _, kind := range contract.KindSpecs {
		b.WriteString(fmt.Sprintf("| `%s` | `%s` |\n", kind.Kind, kind.GoName))
	}
	b.WriteString("\n")

	b.WriteString("## Types\n\n")
	renderNodeMarkdown(&b, contract)
	for _, doc := range contract.Types {
		renderTypeMarkdown(&b, doc)
	}

	return b.String(), nil
}

// renderNodeMarkdown 单独展开 `Node` 的判别联合结构，避免读者先跳到 TS 才看懂 `spec`。
func renderNodeMarkdown(b *strings.Builder, contract *Contract) {
	b.WriteString("### Node\n\n")
	b.WriteString("| json | Go type | TS type | required | notes |\n")
	b.WriteString("|---|---|---|---|---|\n")
	b.WriteString("| `id` | `string` | `string` | yes |  |\n")
	b.WriteString("| `kind` | `NodeKind` | `FlowNodeKind` | yes | Selects the spec type. |\n")
	b.WriteString("| `allow_fail` | `bool` | `boolean` | no |  |\n")
	b.WriteString("| `retry` | `*int` | `number` | no |  |\n")
	b.WriteString("| `retry_backoff_ms` | `*int` | `number` | no |  |\n")
	b.WriteString("| `timeout_ms` | `*int` | `number` | no |  |\n")
	b.WriteString("| `spec` | `json.RawMessage` | `FlowNodeSpec` | yes | Decode with the type mapped from `kind`. |\n\n")
}

// renderTypeMarkdown 为普通结构体输出字段表格。
func renderTypeMarkdown(b *strings.Builder, doc TypeDoc) {
	b.WriteString("### " + doc.GoName + "\n\n")
	if doc.Note != "" {
		b.WriteString(doc.Note + "\n\n")
	}
	b.WriteString("| json | Go field | Go type | TS type | required | notes |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, field := range doc.Fields {
		required := "yes"
		if field.Optional {
			required = "no"
		}
		b.WriteString(fmt.Sprintf("| `%s` | `%s` | `%s` | `%s` | %s | %s |\n",
			field.JSONName,
			field.GoName,
			field.GoType,
			field.TSType,
			required,
			field.Note,
		))
	}
	b.WriteString("\n")
}

// RenderTypeScript 将合同模型渲染成下游前端可直接消费的稳定 TS 定义。
func RenderTypeScript(contract *Contract) (string, error) {
	if contract == nil {
		return "", fmt.Errorf("nil contract")
	}

	var b strings.Builder
	b.WriteString("// Code generated by flowcontractgen. DO NOT EDIT.\n\n")
	b.WriteString("export type JSONPrimitive = string | number | boolean | null\n")
	b.WriteString("export type JSONValue = JSONPrimitive | JSONObject | JSONArray\n")
	b.WriteString("export type JSONObject = { [key: string]: JSONValue }\n")
	b.WriteString("export type JSONArray = JSONValue[]\n\n")

	for _, enum := range contract.Enums {
		b.WriteString(fmt.Sprintf("export const %s = %s as const\n", enum.ConstName, quoteArray(enum.Values)))
		b.WriteString(fmt.Sprintf("export type %s = (typeof %s)[number]\n\n", enum.TSName, enum.ConstName))
	}

	for _, doc := range contract.Types {
		if doc.GoName == "Graph" {
			continue
		}
		renderTypeScriptInterface(&b, doc)
	}

	renderNodeTypeScript(&b, contract)
	renderGraphTypeScript(&b)

	return b.String(), nil
}

// renderTypeScriptInterface 输出单个结构体的 TS interface。
func renderTypeScriptInterface(b *strings.Builder, doc TypeDoc) {
	b.WriteString(fmt.Sprintf("export interface %s {\n", doc.TSName))
	for _, field := range doc.Fields {
		optional := ""
		if field.Optional {
			optional = "?"
		}
		b.WriteString(fmt.Sprintf("  %s%s: %s\n", field.JSONName, optional, field.TSType))
	}
	b.WriteString("}\n\n")
}

// renderNodeTypeScript 生成 `FlowNode` 的 kind-tagged 判别联合定义。
func renderNodeTypeScript(b *strings.Builder, contract *Contract) {
	b.WriteString("export interface FlowNodeBase {\n")
	b.WriteString("  id: string\n")
	b.WriteString("  allow_fail?: boolean\n")
	b.WriteString("  retry?: number\n")
	b.WriteString("  retry_backoff_ms?: number\n")
	b.WriteString("  timeout_ms?: number\n")
	b.WriteString("}\n\n")

	b.WriteString("export interface FlowNodeSpecByKind {\n")
	for _, kind := range contract.KindSpecs {
		b.WriteString(fmt.Sprintf("  %s: %s\n", kind.Kind, kind.TSName))
	}
	b.WriteString("}\n\n")

	b.WriteString("export type FlowNodeSpec = FlowNodeSpecByKind[FlowNodeKind]\n\n")
	b.WriteString("export type FlowNode =\n")
	for i, kind := range contract.KindSpecs {
		prefix := "  |"
		if i == 0 {
			prefix = "  "
		}
		b.WriteString(fmt.Sprintf("%s (FlowNodeBase & { kind: %q; spec: %s })\n", prefix, kind.Kind, kind.TSName))
	}
	b.WriteString("\n")
}

// renderGraphTypeScript 输出顶层图结构，作为前端读写 Flow 草稿的入口类型。
func renderGraphTypeScript(b *strings.Builder) {
	b.WriteString("export interface FlowGraph {\n")
	b.WriteString("  nodes: FlowNode[]\n")
	b.WriteString("  edges: FlowEdge[]\n")
	b.WriteString("}\n")
}

// FileChanged 用于 `-check` 模式下判断目标产物是否与当前渲染结果一致。
func FileChanged(path string, want string) (bool, error) {
	got, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return true, nil
		}
		return false, err
	}
	return string(got) != want, nil
}

// WriteFileIfChanged 仅在内容实际变化时落盘，避免无意义更新时间戳。
func WriteFileIfChanged(path string, content string) (bool, error) {
	changed, err := FileChanged(path, content)
	if err != nil {
		return false, err
	}
	if !changed {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return false, err
	}
	return true, nil
}

// quoteArray 将字符串枚举渲染成 TS `as const` 可用的字面量数组。
func quoteArray(values []string) string {
	var parts []string
	for _, value := range values {
		parts = append(parts, fmt.Sprintf("%q", value))
	}
	return "[" + strings.Join(parts, ", ") + "]"
}
